-- B-416 — re-derive food_items.proteins from stored ingredients_notes.
-- GENERATED by scripts/backfill-proteins.mjs — do not hand-edit.
-- Class-B primary re-key: ON (PM-ratified 2026-07-25)
-- Rows scanned: 62 · rows changed: 37
-- Primaries rewritten: 10 (Class B, PM-ratified: 3 · Class A, always permitted: 7)
--
-- Additive only: no statement removes a stored protein key. Idempotent: a
-- second run over the post-state produces zero statements.

BEGIN;
UPDATE food_items SET primary_protein = 'duck', proteins = ARRAY['duck', 'chicken', 'turkey']::text[] WHERE id = '814ded7d-2e84-4ecc-84c7-484ac19a6bb5';
UPDATE food_items SET primary_protein = 'whitefish', proteins = ARRAY['whitefish', 'fish', 'tuna']::text[] WHERE id = 'df83b25b-c3d4-4add-b58e-c8ea4f8d19ba';
UPDATE food_items SET primary_protein = 'beef', proteins = ARRAY['beef', 'chicken']::text[] WHERE id = '44f5d21d-9927-438a-8090-8ab5b0b322db';
UPDATE food_items SET primary_protein = 'beef', proteins = ARRAY['beef', 'fish']::text[] WHERE id = '4d0ef2e8-5950-4b35-addc-f071ee0f6898';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'fish']::text[] WHERE id = 'b7928207-7407-41bf-bea2-b2173dbfc157';
UPDATE food_items SET primary_protein = 'whitefish', proteins = ARRAY['whitefish', 'chicken', 'crab']::text[] WHERE id = '6ed27386-b33b-4d9e-8be4-eb8e64cb336e';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'pork']::text[] WHERE id = '36fce973-35cb-4aee-b741-4087ff784341';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'turkey', 'egg']::text[] WHERE id = '040e864c-bc1c-4e8d-ba12-687e64fac351';
UPDATE food_items SET primary_protein = 'duck', proteins = ARRAY['duck', 'pork', 'turkey']::text[] WHERE id = 'f1239932-a8f6-4165-9ebd-462a242ae7d7';
UPDATE food_items SET primary_protein = 'tuna', proteins = ARRAY['tuna', 'chicken', 'turkey', 'egg']::text[] WHERE id = 'b20c19a0-1ec6-4b8a-b748-67098b7fade4';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'turkey', 'egg']::text[] WHERE id = '887deaae-8724-42b4-9146-b0141605ca8d';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'herring']::text[] WHERE id = '13b0c9f9-0914-4fd4-a91b-caead2d9015a';
UPDATE food_items SET primary_protein = 'whitefish', proteins = ARRAY['whitefish', 'fish', 'chicken', 'tuna']::text[] WHERE id = '72a52afb-ddfc-40ce-b929-124b8562cd2c';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'poultry', 'turkey']::text[] WHERE id = '2069a396-0ab3-4e7c-907f-1caf50198f37';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'turkey']::text[] WHERE id = '1982a8f9-d5fc-4ea4-95b7-e0a3a57d933f';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'turkey']::text[] WHERE id = '0446cbf8-0c48-49e5-8076-874cb2d8f96c';
UPDATE food_items SET primary_protein = 'turkey', proteins = ARRAY['turkey', 'fish', 'chicken']::text[] WHERE id = '6edfb506-8943-4374-956a-354c2974950f';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'egg', 'cheese']::text[] WHERE id = 'ef30f24b-58ba-4ffd-9eef-d7cd62ee63f0';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'turkey']::text[] WHERE id = 'b67b2819-79e4-48d0-85c8-06a60a2d7a01';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'turkey', 'cheese']::text[] WHERE id = 'aca34504-fb3c-4e0f-9770-d78b05afbf81';
UPDATE food_items SET primary_protein = 'rabbit', proteins = ARRAY['rabbit']::text[] WHERE id = 'aa4f500e-dd63-447f-ba9f-590438470ab7';
UPDATE food_items SET primary_protein = 'rabbit', proteins = ARRAY['rabbit']::text[] WHERE id = '53dfa6ae-b1ea-4ba8-a17c-d847e87e3489';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'poultry', 'egg']::text[] WHERE id = '8c5db43a-0fe1-4323-a905-d294d85dde81';
UPDATE food_items SET primary_protein = 'turkey', proteins = ARRAY['turkey', 'egg']::text[] WHERE id = 'bf51b6b8-c6e5-477c-9504-4b71c3a92db8';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'beef', 'cheese']::text[] WHERE id = '3e0e5cdc-2ad0-4e65-8769-0d007ee13bf3';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'cheese']::text[] WHERE id = '97608e03-e947-44f4-bfa3-da9d4d87cb2d';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken']::text[] WHERE id = '861ab2e1-13d6-4189-87cc-ac4a3d89a191';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'cheese']::text[] WHERE id = '14953455-dd4e-403f-ab5c-940fe92e44fa';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'cheese']::text[] WHERE id = '17e8b37a-043c-491c-903a-3e79c7c0d779';
UPDATE food_items SET primary_protein = 'rabbit', proteins = ARRAY['rabbit', 'duck', 'chicken']::text[] WHERE id = 'ff2e30b1-3b82-4b5e-97fc-0c598f564221';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'egg']::text[] WHERE id = '90fea001-850c-4943-b47b-0f19860029f5';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'egg', 'milk']::text[] WHERE id = '1cb64256-3a36-4c45-ad9a-91ae4ce4703e';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'egg']::text[] WHERE id = '5fafd7a2-fdb1-4804-abf7-a8ec6012116d';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken']::text[] WHERE id = '69e79e22-5363-4a2b-8030-8e8e86e3be4d';
UPDATE food_items SET primary_protein = 'tuna', proteins = ARRAY['tuna', 'chicken', 'egg']::text[] WHERE id = '4d4ec124-8df6-4c39-ac82-9a1e1c69bed3';
UPDATE food_items SET primary_protein = 'chicken', proteins = ARRAY['chicken', 'herring']::text[] WHERE id = '1bb45817-ac08-4b00-accd-8c98ca6893a7';
UPDATE food_items SET primary_protein = 'lamb', proteins = ARRAY['lamb', 'fish', 'tuna']::text[] WHERE id = '07cae434-0c0b-4f10-a613-d3a66e1efc50';
COMMIT;
