// Culprit's own operating model, written to the PM. Every claim here was fact-checked
// against the repo on 2026-10-02 (four isolated reviewers, 103 claims, 49 corrected).
export default {
  source: 'scripts/how-we-work/culprit.mjs',
  title: 'The Culprit Operating Model',
  eyebrow: 'Culprit · how you make it · 2 October 2026',
  h1: 'The Culprit Operating Model',
  lede: "You build Culprit with a rotating crew of Claude sessions. You decide; the sessions do everything else, often several at once, and none of them remembers the one before. It works because every session starts by reading a written record and ends by writing to it, and because the rules that matter are enforced by the build instead of by anyone's memory. The gauges below were measured on 2 October.",
  stats: [
    { v: '156', l: 'waiting on you' },
    { v: '49 of 52', l: 'open PRs are drafts' },
    { v: '88', l: 'PRs merged in 7 days' },
    { v: '1.3 h', l: 'median open to merge' },
    { v: '146', l: 'sessions since the last retro' },
    { v: '371 B', l: 'CLAUDE.md headroom' },
  ],
  human: { label: 'YOU' },

  loop: {
    eyebrow: 'Your part',
    h2: 'Your week',
    deck: 'What the system asks of you, and where it waits on you.',
    steps: [
      { when: 'To start work', what: "Paste a Linear issue's prompt, or run `/dispatch` and name the rows to start." },
      { when: 'Early in a build', what: 'Read the plan and say go. Only a mechanical fix skips this.' },
      { when: 'During a session', what: 'Rule on decision briefs. React to mock rounds, republished to the same URL each round.' },
      { when: 'Before a live write', what: "Approve a dispatched row's migration before it is applied. Do the App Store and console steps only you can reach." },
      { when: 'After a push', what: 'Run the QA script on your phone, then merge, usually the next morning. A dispatched session may merge its own PR once every check is green.' },
      { when: 'At each wrap', what: 'Take the QA script, the next prompt, and One thing to learn.' },
      { when: 'Between sessions', what: 'Work the Waiting on PM queue: 156 open, about three new a day.' },
      { when: 'Monthly', what: '`/coach` reads how you operated and hands you one habit.' },
    ],
    aside: [
      '**Your constraint is deciding, not merging.** 88 PRs merged in the last seven days, at a median of 1.3 hours from open to merge. Waiting on PM went from 10 on 20 August to 97 on 11 September to 156 today, and 71 items are older than 30 days.',
      '**The fix is ruled and not running.** On 27 September you set the cadence: two 30 minute dockets a week and one device sitting per TestFlight cut (CUL-1366). Its build session has not run yet.',
      '**The second queue is drafts.** 49 of 52 open PRs are drafts. The oldest is 112 days old.',
    ],
  },

  fig1: {
    eyebrow: 'The unit of work · hours',
    h2: 'One session',
    deck: 'Eight stations, the same every time, whatever the task. You step in at five points. Everything the session learns lands in one of four stores, so the next session starts from the record.',
    band: 'Pick the work, rule on briefs, test on your phone, merge.',
    betweenLabel: 'BETWEEN SESSIONS',
    between: 'your queue: 156 open · mock round reactions',
    handoffs: [
      { lines: ['you pick the issue,', 'or run `/dispatch`'] },
      { lines: ['a plan for you,', 'then your go'] },
      { lines: ['a brief for you', 'or a conflict'] },
      { lines: ['you test it', 'on your phone'] },
      { lines: ['QA script, next', 'prompt; you merge'] },
    ],
    frameLabel: 'ONE SESSION · ONE BRANCH · ONE PR',
    stations: [
      { name: 'Launch', lines: ["a Linear issue's", 'prompt, or', '`/dispatch`'] },
      { name: 'Claim', lines: ['a comment names', 'the branch; stale', '>24 h with no PR'] },
      { name: 'Orient', lines: ['`CLAUDE.md` loads;', 'then the issue', 'and its spec'] },
      { name: 'Plan', lines: ['BUILD: a plan,', 'then your go', 'DISCOVERY: brief'] },
      { name: 'Build', lines: ['lenses speak', 'unprompted;', 'skills autoload'] },
      { name: 'Review', lines: ['subagents with', 'no build context', 'try to break it'] },
      { name: 'Ship', lines: ['tsc + jest gate', 'the push; draft', 'PR names issues'] },
      { name: 'Wrap', lines: ['`/wrap`: DoD,', 'record, outcome,', 'One thing, prompt'] },
    ],
    storeArrows: {
      0: { lines: ['reads the', 'run order'] },
      1: { lines: ['claim', 'comment'] },
      2: { lines: ['rules and', 'the spec'] },
      4: { lines: ['code, specs,', 'lessons'] },
      6: { lines: ['draft PR'] },
      7: { lines: ['the record'] },
    },
    stores: [
      { eyebrow: 'LINEAR · THE WORK', title: 'What to do, and who has it', lines: ['Project = a track and its run order', 'Issue = the spec; newest comment wins', 'Claim and outcome, as comments', 'Waiting on PM: your queue, 156 open'] },
      { eyebrow: 'GIT DOCS · THE READ PATH', title: 'What a session must read to build it right', lines: ['`CLAUDE.md`: the rulebook, loaded every session, byte capped', '56 specs; 70+ mock pages, each round republished in place', '`personas.md`; `engineering-lessons.md` (44, dated)', 'Test for a doc: needed to build it right? Git. Else Linear.'] },
      { eyebrow: 'GITHUB · THE PROOF', title: 'What actually shipped', lines: ['One PR per session, squash merged', 'CI: types, jest with 43 guards, Deno', 'A merge closes every issue it names', 'and deploys changed Edge Functions'] },
      { eyebrow: 'DOCS/SESSIONS', title: 'The story', lines: ['one file per', 'session; nobody', "edits another's;", '522 so far'] },
    ],
    returnLabel: 'the outcome comment releases the claim; anything you owe lands on your queue',
    caption: 'A session has no memory, so the record does the remembering. Stations 01 and 03 read it; 02, 05, 07 and 08 write to it. Only a mechanical fix skips the plan at 04, and anything touching access control, deletion or export never does. Since 29 September a session launched by `/dispatch` may merge its own PR once every check is green.',
    legend: ['a handoff to or from you', 'reads and writes the record', 'next station'],
    aria: 'One session runs eight stations: launch, claim, orient, plan, build, review, ship, wrap. You hand down the prompt and the go-ahead; the session hands up its plan, decision briefs, the QA script and the next prompt; you test on your phone and merge after the wrap. Stations read from and write to four stores: Linear, the git docs, GitHub and the session records.',
  },

  fig2: {
    eyebrow: 'The unit of delivery · weeks',
    h2: 'One track',
    deck: 'How a feature goes from a question to every account. Work alternates between the sessions and you, and every crossing carries a named artifact, so you never rebuild context to answer.',
    phases: ['DISCOVER', 'DECIDE', 'SPECIFY', 'BUILD AND SHIP'],
    nodes: [
      { name: 'Research brief', lines: ['dated evidence,', 'then frozen'] },
      { name: 'Mock round N', lines: ['one URL, round', 'after round'] },
      { name: 'Design critique', lines: ['isolated lenses,', 'a verifier each'] },
      { name: 'Decision briefs', lines: ['2 to 4 options,', 'a pick or dissent'] },
      { name: 'The spec', lines: ['§0 decisions to', 'kickoff prompts'] },
      { name: 'The run order', lines: ['PR by PR, on its', 'Linear project'] },
      { name: '`/dispatch`', lines: ['proposes ready', 'rows, ≤3 in flight'] },
      { name: 'Build sessions', lines: ['each is Fig. 1;', 'most behind flags'] },
    ],
    human: [
      { under: 1, name: 'You react', line: 'to its R-x prompts', down: 'round N', up: 'reactions' },
      { under: 3, name: 'You rule', line: 'brief by brief', down: 'brief', up: 'ruling' },
      { under: 6, name: 'You pick rows', line: 'or a standing yes', down: 'proposal', up: 'picks' },
      { under: 7, name: 'You test', line: 'or waive; then GA', down: 'QA script', up: 'verdict' },
    ],
    footnote: 'Indigo boxes are you. Each pair of arrows is a handoff and its answer; your reactions turn round N into round N+1.',
    caption: "Each track is a Linear project whose page carries the run order: which PR follows which, which may run side by side, and which never at the same time. Since 28 September `/dispatch` reads that page against GitHub, says why it holds each row back, and launches only while fewer than three of the project's rows are in flight. Most new surfaces now ship dark behind a beta flag and graduate in four steps: the flip for every account, a removal PR that deletes the gate and the old path, one native build, a closeout. Between tracks, Quick Win sweeps take the small items.",
    aria: 'A track runs left to right in four phases: discover, decide, specify, build and ship. Sessions produce a research brief, mock rounds, a design critique, decision briefs, the spec, the run order, dispatch proposals and the build sessions. You react to each mock round, rule on each brief, pick which rows start, and test before calling GA.',
  },

  ladder: {
    eyebrow: 'The quality system',
    h2: 'How a rule gets teeth',
    deck: 'Four ways to bring judgment to bear, from softest to hardest. When the same class of mistake comes back, the check that should have caught it moves up a rung.',
    scale: ['Remembered', 'Enforced'],
    rungs: [
      { name: 'Persona', what: 'A lens Claude adopts in context. The routing table says which lenses each surface expects, and every Definition of Done names them: N/A is fine, silence is not.', fires: 'when remembered; the sign off line makes it hard to forget', example: 'Jordan: can I do this in under 10 seconds while my dog is being weird?', count: '10 on the roster, 3 specialists' },
      { name: 'Skill', what: 'Instructions that load themselves when a matching file path or keyword appears.', fires: 'whenever the trigger matches', example: '`clinical-guardrails` loads on any per incident AI read: one sample may escalate, never reassure.', count: '5 skills' },
      { name: 'Subagent', what: 'A reviewer in a fresh context, briefed but never shown the build conversation, so it cannot share its optimism. It returns a verdict.', fires: 'when invoked; the Definition of Done requires one for clinical and statistical logic and for access control', example: '`adversarial-reviewer` must name the counterexample it tried. A bare ✓ is not a review.', count: '6 subagents' },
      { name: 'Guard', what: 'A test that reads the source and fails the build. Where an exemption exists, it is a reasoned marker at the site or a registry entry in the guard.', fires: 'on every PR in required CI, and before each push through the git hook', example: "`recordPetName.test.ts` fails if a record screen falls back to the active pet's name.", count: '43 guard tests' },
    ],
    pathLabel: "A lesson's path, with the real example",
    path: [
      { k: 'The mistake', text: '`CLAUDE.md` was cut in half on 2 September. Nine days later it was bigger than it had been two weeks before the cut.' },
      { k: 'The lesson', text: 'The September retro wrote it up as L3: a budget without a structural fix only buys time, and a cap on count is not a cap on size.' },
      { k: 'The rule', text: "In `CLAUDE.md`, a few lines: an addition here is paid for by a deletion here. The story lives in the retro and the guard's own header." },
      { k: 'The guard', text: '`claudeMdBudget.test.ts` fails the build when the file outgrows its byte ceiling, and when a trim leaves the ceiling stale. The ceiling is never raised to go green.' },
    ],
  },

  ref: {
    eyebrow: 'Reference',
    h2: 'The parts that hold it together',
    before: [{
      h3: 'Who decides what',
      wide: true,
      rows: [
        ['Sessions, without asking', 'The seven principles, Pets > $, the engineering hard constraints and the two safety invariants. Small calls go in as team defaults you can veto.'],
        ['Sessions stop and ask', 'A non trivial BUILD plan; anything touching RLS, Storage, deletion or export; a persona conflict; a spec edit; new scope.'],
        ['Only you', 'Rulings, device checks, App Store and console steps, and merging anything `/dispatch` did not launch.'],
        ['Never, for anyone', 'Deploying except by merging. Committing to main.'],
        ['Handed off already', 'The standing yes for low risk `/dispatch` rows and self merge when green (29 September). Edge Function deploys on merge.'],
      ],
    }],
    state: {
      h3: 'Where state lives',
      rows: [
        ['What is in flight, and who has it', 'Linear: In Progress, plus the claim comment naming the branch'],
        ['What comes next', "Linear: the project's run order; outside a track, Todo by priority"],
        ['What is waiting on you', 'Linear: the Waiting on PM label'],
        ['How to build it correctly', 'Git: `CLAUDE.md`, the spec, the migrations'],
        ['What happened, and why', 'Git: `docs/sessions/` and the PR bodies'],
        ['What is still undecided', 'Git: the Open Questions table (12 rows). Most live calls are briefs on Waiting on PM issues.'],
      ],
      note: '`STATUS.md` is a pointer card no session writes to: which of these to open, the live tracks, the holds. A session edits `CLAUDE.md` on its own, inside the byte ratchet; a spec edit needs your yes; a frozen brief is corrected only by a dated addendum.',
    },
    clocks: {
      h3: 'The clocks',
      rows: [
        ['Every push', 'The git hook runs the type check and the full jest suite. It can be skipped; CI cannot.'],
        ['Every PR', 'Required checks: types, jest (the guards run inside it), Deno. No bypass. Jest also reruns in three far time zones, advisory until CUL-586. Engine changes print a scorecard that reports and never blocks.'],
        ['Every merge', 'Squash. Every issue the PR names closes, so a task that spans PRs gets one sub-issue per PR. Changed Edge Functions deploy and record themselves unless the manifest holds them.'],
        ['Every migration', 'Its own PR with a safety preflight, applied live before any code that needs it merges.'],
        ['Every session', 'Claim, orient, work, `/wrap`: one PR, one record, the next prompt, One thing to learn.'],
        ['Every mock round', 'Same URL each round. After you react, one proposal with a ledger mapping each reaction to what moved.'],
        ['A TestFlight cut', 'By hand, in its own session. Server code is live on merge; the app reaches owners only here.'],
        ['Most weeks', 'A Quick Win sweep ships the small items and tags the rest with the sitting each needs.'],
        ['Weekly', 'The suite runs with the clock moved forward.'],
        ['Monthly', '`/coach`, run by hand.'],
        ['The retro', 'Ruled every ~10 sessions, but nothing fires it. Run 19 July and 11 September; 146 sessions since.'],
      ],
    },
    talk: {
      h3: 'How you asked to be briefed',
      brief: {
        label: 'Decision brief · a real ruling, in the format',
        deciding: 'Whether Waiting on PM becomes a workflow state or stays a label.',
        rec: "(a) A Needs PM state, the September retro's pick:",
        options: 'exclusive, and it empties when an issue closes. (b) Keep the label and strip it from closed issues every grooming pass.',
        consequence: 'You ruled (b) on 2 October: no migration, and the drain became a groomer step.',
      },
      bullets: [
        ['Rule from the brief alone (7 Aug).', 'About four lines: options with one recommended, or the dissent named.'],
        ['Mock what you change (7 Aug).', 'A visual choice is drawn side by side, never only described.'],
        ['Plain English first (26 Aug).', 'Every issue opens with a TL;DR you can read cold.'],
        ['One proposal per reaction round (9 Sep).', 'Retired directions leave the page; a ledger maps each reaction to what moved.'],
        ['A rule is a floor with a date on it (17 Sep).', 'A better idea that breaks one arrives as a brief, never as a quiet workaround.'],
        ['Conflicts come to you.', 'Both sides are named, then the session stops until you rule.'],
        ['Unanswered after a session:', 'a provisional decision, flagged for you to confirm.'],
      ],
    },
    laws: {
      h3: 'Laws worth carrying over',
      items: [
        ['Prose fires approximately never.', 'A guard or a scheduled job has zero recorded misses. There is no third tier.', 'retro L2'],
        ['Every queue needs a mandated remove,', 'or it is the old checklist in a new store.', 'retro L1'],
        ['A detector that cannot fire', 'is indistinguishable from a clean board.', 'retro L7'],
        ['A deliverable only on an unmerged branch', 'does not exist.', 'retro L4'],
        ['Fan out the read, serialize the write.', '', 'retro, September'],
        ['Verify the premise at file:line', 'before building on it.', 'event taxonomy spec'],
      ],
      leak: [
        '**Where it leaks: your queue.** Every session is told to add to Waiting on PM, and nothing removes an open item. On 2 October you kept it a label (CUL-923 canceled), and each grooming pass now strips it from closed issues. That clears the dead entries, not the inflow.',
      ],
    },
  },

  kit: {
    eyebrow: 'Porting it',
    h2: 'You already built the kit',
    deck: '`operating-kit/` (#976, 29 September) is the portable copy of this engine. [The Operating Kit](https://claude.ai/artifact/41Qscq43pii1umUVqLAm1D) is its map, committed as `docs/how-we-work-template.html`.',
    intro: [
      "To start a new project, paste `operating-kit/BOOTSTRAP.md` §0 into its first session. That session interviews you in four rounds, fills the templates, and installs everything as one PR.",
      "**Kept in sync by: nothing.** The kit is a snapshot of 29 September, and its README asks future sessions to copy lessons across. That is a prose rule (retro L2), and the two have already drifted.",
    ],
    table: {
      h3: 'Where the kit and this repo differ, 2 October',
      head: ['Part', 'The kit', 'This repo', 'Ahead'],
      rows: [
        ['Your queue', '`Needs PM` as a workflow state', 'The label, stripped from closed issues by the groomer (your 2 October ruling)', 'Your call'],
        ['The retro', 'A `/retro` command, fired by the start hook printing RETRO DUE', 'Prose only; nothing has fired it since 11 September', 'Kit'],
        ['The start hook', "Unshallows the clone and prints the manual's byte count", 'Runs `npm install` only', 'Kit'],
        ['Record only PRs', 'Open ready to merge', 'Open as drafts', 'Kit'],
        ['`/dispatch`', 'Before the standing yes and self merge', 'Standing yes; a dispatched PR may merge itself when green', 'Repo'],
        ['The groomer', 'Condensed, 29 September', 'Retirement sweep, 7 day veto, label strip (2 October)', 'Repo'],
        ['Your learning loop', 'None', 'One thing per session, monthly `/coach`', 'Repo'],
      ],
      note: 'Not in git at all, so no copy carries it: the Linear prompt template, the GitHub ruleset, the Linear and GitHub integration, and the production environment that holds the deploy token. Recreate these by hand.',
    },
  },

  footer: 'Fact checked against the repo on 2 October 2026 by four isolated reviewers: 103 claims, 49 corrected before publishing. Sources: `CLAUDE.md`, `docs/personas.md`, `.claude/` (7 commands, 6 subagents, 5 skills, 1 workflow), `guards/`, `.github/workflows/`, both process retros, `operating-kit/`. Scale since May 2026: about 1,000 PRs, 522 session records, about 1,450 Linear issues. The generic version: [The Operating Kit](https://claude.ai/artifact/41Qscq43pii1umUVqLAm1D).',
};
