// The generic operating model: the map of operating-kit/. Concepts are named by role and
// by the kit file that installs them. Drafted by two independent agents (tool agnostic and
// Claude Code native), judged into one, then corrected against the repo on 2026-10-02.
export default {
  source: 'scripts/how-we-work/template.mjs',
  title: 'The Operating Kit',
  eyebrow: 'operating-kit/ · the map · snapshot of 29 September 2026',
  h1: 'The Operating Kit',
  lede: 'One person decides, and a rotating crew of AI coding sessions does the rest, often several at once, none of them remembering the one before. The engine works because every session starts by reading a written record and ends by writing to it, and because each rule that matters lives in a file the harness loads, runs or tests. This page maps every part to its job and to the kit file that installs it. Anything in ‹angle quotes› is yours to fill.',
  stats: [
    { v: '1', l: 'human who decides' },
    { v: '5', l: 'isolated reviewers' },
    { v: '7', l: 'rituals as commands' },
    { v: '3', l: 'skills and a template' },
    { v: '12', l: 'laws, each from a measurement' },
    { v: '~20 KB', l: 'rulebook to start' },
  ],
  human: { label: 'YOU' },

  fig1: {
    eyebrow: 'The unit of work · hours',
    h2: 'One session',
    deck: 'Eight stations, the same every time, whatever the task. You step in at five points. Everything the session learns lands in one of four stores, so the next session starts from the record.',
    band: 'Pick the work, rule on briefs, try it live, merge.',
    betweenLabel: 'BETWEEN SESSIONS',
    between: 'your queue, cleared in sittings · mock rounds',
    handoffs: [
      { lines: ['you pick the issue,', 'or run `/dispatch`'] },
      { lines: ['a plan for you,', 'then your go'] },
      { lines: ['a brief for you', 'or a conflict'] },
      { lines: ['you try it on', 'the real device'] },
      { lines: ['QA script, next', 'prompt; you merge'] },
    ],
    frameLabel: 'ONE SESSION · ONE BRANCH · ONE PR',
    stations: [
      { name: 'Launch', lines: ["the issue's", 'launch prompt,', 'or `/dispatch`'] },
      { name: 'Claim', lines: ['a comment names', 'the branch; stale', '>24 h with no PR'] },
      { name: 'Orient', lines: ['`CLAUDE.md` loads;', 'then the issue', 'and its spec'] },
      { name: 'Plan', lines: ['BUILD: a plan,', 'then your go', 'DISCOVERY: brief'] },
      { name: 'Build', lines: ['lenses speak', 'unprompted;', 'skills autoload'] },
      { name: 'Review', lines: ['`.claude/agents`', 'in fresh context', 'try to break it'] },
      { name: 'Ship', lines: ['`pre-push` gate;', 'the PR names', 'what it finishes'] },
      { name: 'Wrap', lines: ['`/wrap`: DoD,', 'record, outcome,', 'next prompt'] },
    ],
    storeArrows: {
      0: { lines: ['reads the', 'run order'] },
      1: { lines: ['claim', 'comment'] },
      2: { lines: ['rules and', 'the spec'] },
      4: { lines: ['code, specs,', 'lessons'] },
      6: { lines: ['the PR'] },
      7: { lines: ['the record'] },
    },
    stores: [
      { eyebrow: 'THE TRACKER · THE WORK', title: 'What to do, and who has it', lines: ['Project = a track and its run order', 'Issue = the spec; newest comment wins', 'Claim and outcome, as comments', 'Your queue: one view, with a drain'] },
      { eyebrow: 'GIT DOCS · THE READ PATH', title: 'What a session must read to build it right', lines: ['`CLAUDE.md`: the rulebook, loaded every session, byte capped', 'Specs, versioned in the header; mocks at one URL each', '`docs/personas.md`; `docs/engineering-lessons.md`', 'Test for a doc: needed to build it right? Git. Else tracker.'] },
      { eyebrow: 'THE CODE HOST · THE PROOF', title: 'What actually shipped', lines: ['One PR per session, squash merged', 'Required CI: types, tests, guards', 'A merge closes every issue it names', 'and deploys, writing its own record'] },
      { eyebrow: 'DOCS/SESSIONS', title: 'The story', lines: ['one file per', 'session; nobody', "edits another's;", 'shipped via #n'] },
    ],
    returnLabel: 'the outcome comment releases the claim; anything you owe lands on your queue',
    caption: 'A session has no memory, so the record does the remembering. Stations 01 and 03 read it; 02, 05, 07 and 08 write to it. Only a mechanical fix skips the plan at 04, and anything touching access control, deletion or export never does. Every label set in mono is a path the kit installs.',
    legend: ['a handoff to or from you', 'reads and writes the record', 'next station'],
    aria: 'One session runs eight stations: launch, claim, orient, plan, build, review, ship, wrap. You hand down the prompt and the go-ahead; the session hands up its plan, decision briefs, the QA script and the next prompt; you try it live and merge after the wrap. Stations read from and write to four stores: the tracker, the git docs, the code host and the session records.',
  },

  fig2: {
    eyebrow: 'The unit of delivery · weeks',
    h2: 'One track',
    deck: 'How a feature goes from a question to every user. Work alternates between the sessions and you, and every crossing carries a named artifact, so you never rebuild context to answer.',
    phases: ['DISCOVER', 'DECIDE', 'SPECIFY', 'BUILD AND SHIP'],
    nodes: [
      { name: 'Research brief', lines: ['dated evidence,', 'then frozen'] },
      { name: 'Mock round N', lines: ['one URL, round', 'after round'] },
      { name: 'Design critique', lines: ['isolated lenses,', 'a verifier each'] },
      { name: 'Decision briefs', lines: ['2 to 4 options,', 'a pick or dissent'] },
      { name: 'The spec', lines: ['§0 decisions to', 'kickoff prompts'] },
      { name: 'The run order', lines: ['PR by PR, on its', 'tracker project'] },
      { name: '`/dispatch`', lines: ['proposes ready', 'rows, ≤3 in flight'] },
      { name: 'Build sessions', lines: ['each is Fig. 1;', 'dark behind a flag'] },
    ],
    human: [
      { under: 1, name: 'You react', line: 'to each prompt', down: 'round N', up: 'reactions' },
      { under: 3, name: 'You rule', line: 'brief by brief', down: 'brief', up: 'ruling' },
      { under: 6, name: 'You pick rows', line: 'or a standing yes', down: 'proposal', up: 'picks' },
      { under: 7, name: 'You try it live', line: 'then turn it on', down: 'QA script', up: 'verdict' },
    ],
    footnote: 'Indigo boxes are you. Each pair of arrows is a handoff and its answer; your reactions turn round N into round N+1.',
    caption: "Each track is a tracker project whose page holds the run order: which PR follows which, which may run side by side, and which never together. `/dispatch` reads that page against the code host, gives a reason for every row it holds back, and launches each ready row as its own session while fewer than three of the project's rows are in flight. A new surface ships dark behind a flag and graduates in four steps: the flip for everyone, a removal PR that deletes the gate and the old path, a release, a closeout. Kit files: `docs/templates/` (research brief, spec, mock round protocol), `.claude/commands/design-critique.md`, `.claude/commands/dispatch.md`.",
    aria: 'A track runs left to right in four phases: discover, decide, specify, build and ship. Sessions produce a research brief, mock rounds, a design critique, decision briefs, the spec, the run order, dispatch proposals and the build sessions. You react to each mock round, rule on each brief, pick which rows start, and try the result live before turning it on.',
  },

  ladder: {
    eyebrow: 'The quality system',
    h2: 'How a rule gets teeth',
    deck: 'Four ways to bring judgment to bear, from softest to hardest. When the same class of mistake comes back, the check that should have caught it moves up a rung.',
    scale: ['Remembered', 'Enforced'],
    rungs: [
      { name: 'Persona', what: 'A lens Claude adopts in context. A routing table says which lenses each surface expects, and the Definition of Done names them: N/A is fine, silence is not.', fires: 'when remembered; the sign off line makes it hard to forget', example: '‹Primary user›: can I do this in ‹time budget› at my worst moment?', file: '`docs/personas.md` from `personas.template.md`' },
      { name: 'Skill', what: 'Instructions in `.claude/skills/‹name›/SKILL.md`. The description lists the paths and words that matter, and Claude loads the body when the task matches.', fires: 'whenever the task matches the description', example: '`ai-output-guardrails` loads on any model output a user reads: one sample may raise a flag, never clear one.', file: '3 skills and `_skill-template`' },
      { name: 'Subagent', what: 'A reviewer in `.claude/agents/`, in a fresh context: briefed, never shown the build conversation, so it cannot share its optimism. It returns a verdict.', fires: 'when invoked; the Definition of Done requires one for ‹your high stakes logic› and for access control', example: '`adversarial-reviewer` must name the counterexample it tried. A bare ✓ is not a review.', file: '5 reviewers in `dot-claude/agents/`' },
      { name: 'Guard', what: 'A test in `guards/` that reads the source and fails the build. Where an exemption exists, it is a reasoned marker at the site or a registry entry in the guard.', fires: 'on every PR in required CI, and before each push through the git hook', example: 'A guard fails the build when raw error text can reach a screen a user reads.', file: '`claudeMdBudget`, `fixtureRoot`, `blankComments`' },
    ],
    pathLabel: "A lesson's path, with project-nyx's example",
    path: [
      { k: 'The mistake', text: 'In project-nyx, `CLAUDE.md` was cut in half. Nine days later it was bigger than it had been two weeks before the cut, because nothing measured it.' },
      { k: 'The lesson', text: 'A budget without a structural fix only buys time, and a cap on count is not a cap on size (law L2).' },
      { k: 'The rule', text: 'Two lines in `CLAUDE.md`: an addition is paid for by a deletion. A pointer sends the reader to the story.' },
      { k: 'The guard', text: '`guards/claudeMdBudget.test.ts` fails the build when the file outgrows its byte ceiling, or a trim leaves the ceiling stale. The ceiling is never raised to go green.' },
    ],
  },

  ref: {
    eyebrow: 'Reference',
    h2: 'The parts that hold it together',
    before: [{
      h3: 'Who decides what',
      wide: true,
      rows: [
        ['Sessions, without asking', '‹Your principles›, ‹your value rule›, the hard constraints and ‹your safety invariants›. Small calls go in as defaults you can veto.'],
        ['Sessions stop and ask', 'A non trivial BUILD plan; anything touching access control, deletion or export; a lens conflict; a spec edit; new scope.'],
        ['Only you', 'Rulings, checks on a real device, store and console steps, and merges outside `/dispatch`.'],
        ['Never, for anyone', 'Deploying except by merging. Committing to main.'],
        ['Hand off once trusted', 'A standing yes for low risk `/dispatch` rows; a dispatched PR merging itself when every check is green; deploy on merge.'],
      ],
    }],
    state: {
      h3: 'Where state lives',
      rows: [
        ['What is in flight, and who has it', 'Tracker: In Progress, plus the claim comment naming the branch'],
        ['What comes next', "Tracker: the project's run order; outside a track, Todo by priority"],
        ['What is waiting on you', "Tracker: one queue view; each item's first line is your single remaining step"],
        ['How to build it correctly', 'Git: `CLAUDE.md`, the spec, the schema source'],
        ['What happened, and why', 'Git: `docs/sessions/` and the PR bodies'],
        ['What is still undecided', 'Git: Open Questions in `CLAUDE.md`; resolved rows move to `docs/decisions-archive.md`'],
        ['Why a rule exists', 'Git: `docs/operating-model.md` and `docs/engineering-lessons.md`'],
      ],
      note: '`STATUS.md` is a pointer card no session writes to. A session edits `CLAUDE.md` on its own, inside the byte ratchet; a spec edit needs your yes; a frozen brief is corrected only by a dated addendum.',
    },
    clocks: {
      h3: 'The clocks',
      rows: [
        ['Session start', "The start hook unshallows a cloud clone, installs, prints the manual's byte count, and says RETRO DUE when it is."],
        ['Every push', 'A git hook runs the type check and the full suite. It can be skipped; CI cannot.'],
        ['Every PR', 'Required checks on a main ruleset with an empty bypass list: types, tests, guards. The suite also runs in far time zones. A check that should only report gets its own workflow file.'],
        ['Every merge', 'Squash. Every issue the PR names closes, so a task that spans PRs gets one sub-issue per PR. Server code deploys and writes its own record. Read back what closed.'],
        ['Every migration', 'Its own PR with a safety preflight, applied before any code that needs it merges.'],
        ['Every session', 'Claim, orient, work, `/wrap`: one PR, one record, the next prompt.'],
        ['After a PR opens', 'At most one scheduled check, about 90 minutes out, only while sibling sessions are landing. Never at `/wrap`, never overnight.'],
        ['Every mock round', 'Same URL each round. After you react, one proposal with a ledger mapping each reaction to what moved.'],
        ['Weekly', 'The suite runs with the clock moved forward.'],
        ['Every ~10 sessions', '`/retro`, when the hook says RETRO DUE. Four questions; it must delete as much as it adds.'],
      ],
    },
    talk: {
      h3: 'How you get briefed',
      brief: {
        label: 'Decision brief · format sample',
        deciding: 'Whether ‹feature› ships to everyone, or dark behind a flag first.',
        rec: '(a) Dark behind a flag, recommended:',
        options: 'you try it on your own account and turn it off without a release. (b) To everyone: faster, and the only way back is a release.',
        consequence: '(a) adds a flag check now and a removal PR at GA.',
      },
      bullets: [
        ['Rule from the brief alone.', 'About four lines: options with one recommended, or the dissent named.'],
        ['Conflicts come to you.', 'Both sides are named, then the session stops until you rule.'],
        ['Plan before code.', 'A BUILD session posts its files and approach and waits; a DISCOVERY session never builds what it was asked to judge.'],
        ['Mock what you change.', 'A visual choice is drawn side by side, republished to the same URL each round.'],
        ['A rule is a floor with a date on it.', 'A better idea that breaks one arrives as a brief: the rule, its date, what it protected, the better thing.'],
        ['Plain English first.', 'Every issue opens with a TL;DR you can read cold, your one step in bold.'],
        ['Two endings.', 'Every push ends with a QA script you can run in three minutes; every session ends with one prompt ready to paste.'],
      ],
    },
    laws: {
      h3: 'The twelve laws',
      items: [
        ['Prose fires approximately never.', 'A guard, a hook or a scheduled job has zero recorded misses. There is no third tier.', 'L1'],
        ['A budget without a structural fix only buys time.', 'A cap on count is not a cap on size.', 'L2'],
        ['A file every session writes', 'becomes a merge conflict magnet and only grows.', 'L3'],
        ['A queue with a mandated add and no mandated remove', 'is the old checklist in a new store.', 'L4'],
        ['A deliverable only on an unmerged branch', 'does not exist.', 'L5'],
        ['A scheduled wake needs an event it can miss,', 'never a state a structural fix already prevents.', 'L6'],
        ['A detector that cannot fire', 'looks exactly like a clean board.', 'L7'],
        ['Fan out the read, serialize the write.', '', 'L8'],
        ['Whatever performed an action', 'writes the record of it, in the same run.', 'L9'],
        ['A check keyed on a signal your own arrival produces', 'cannot tell you apart from a collision.', 'L10'],
        ['The isolated reviewer', 'catches what the build conversation cannot.', 'L11'],
        ['Verify the premise at file:line', 'before building on it.', 'L12'],
      ],
      leak: [
        '**The laws port; the numbers are tuned.** 24 hours to stale, three in flight, a retro every ten sessions: defaults for one person running a few sessions a day. project-nyx once ran 26 in a day. Retune them at the first retro. Full text: `docs/operating-model.md`.',
      ],
    },
    extra: [{
      h3: 'What goes wrong',
      items: [
        ['A file every session writes.', 'Parallel sessions edit the same lines, and a hurried resolution ships two versions of the truth. Give each session its own new file.'],
        ['The rulebook regrows after every trim.', 'A cap on the number of entries held while each entry kept growing. Only a byte ratchet in the test suite has held.'],
        ['Your queue only grows.', 'Sessions are told to add and nothing is told to remove. Design the drain before the queue, and clear it in sittings by kind.'],
        ['A ritual written only as prose never fires.', 'project-nyx ran its retro twice in over 500 sessions. Compute the trigger in the start hook.'],
        ['A check that cannot fail reads as health.', 'Break the source on purpose and watch every check fail once.'],
        ['A PR closes issues it only mentioned.', 'Every issue named in a title or body closes on merge. Name only what the PR finishes, then read back.'],
        ['Deliverables strand on drafts.', 'A session with no work PR opens its record PR ready to merge.'],
        ['Mechanical fixes land and human ones do not.', 'The board gets cleaner while your queue goes unread. Print the queue count where every session shows it.'],
        ['The kit is a snapshot.', 'The source keeps learning after the copy. Diff the kit against its source before you install it.'],
      ],
    }],
  },

  kit: {
    eyebrow: 'Installing it',
    h2: 'Start here',
    deck: "Paste `operating-kit/BOOTSTRAP.md` §0 into the new repo's first session. It interviews you in four rounds, fills every ‹placeholder›, and installs the parts below as one PR, in roughly this order.",
    items: [
      { title: 'A rulebook the agent loads every session.', detail: 'Roster, hard constraints, each convention as a rule plus its enforcement, the session protocol, the brief shape. Start near 20 KB; stories go in the lessons file.', file: '`CLAUDE.md` from `CLAUDE.template.md`' },
      { title: 'A cast of lenses with a routing table.', detail: '‹Primary user›, ‹ambiguity user› and ‹domain expert› among about ten, plus which lenses each surface expects.', file: '`docs/personas.md` from `docs/personas.template.md`' },
      { title: 'A tracker where the issue is the spec.', detail: 'Newest comment wins. A claim comment names the branch; an outcome comment releases it. A queue view for you, an issue shape that opens with a TL;DR, a launch prompt that only routes.', file: 'tracker settings, `BOOTSTRAP.md` §4' },
      { title: 'A pointer card and one record per session.', detail: 'The card changes only when a track starts or ends. Each record is a new file, written once, saying shipped via #n.', file: '`STATUS.md` from `STATUS.template.md`; `docs/sessions/README.md`' },
      { title: 'A start ritual and a close ritual.', detail: '`/kickoff` claims and orients; `/wrap` runs the done list, writes the record, releases the claim and writes the next prompt.', file: '`.claude/commands/`: `kickoff`, `wrap`, `handoff`, `pm-review`' },
      { title: 'Isolated reviewers for what can hurt someone.', detail: 'Each names the counterexample or attack it tried. Required for ‹your high stakes logic› and for access control.', file: '`.claude/agents/`: five reviewers' },
      { title: 'Invariants that load themselves.', detail: 'One skill per rule that must fire every time, with shipped code as the canonical example.', file: '`.claude/skills/`: `ai-output-guardrails`, `product-voice`, `backlog-groomer`' },
      { title: 'A narrow interface for you.', detail: 'Decision briefs, a mock of every visual change, a QA script per push, a paste ready prompt per session. You decide, try and merge.', file: '`CLAUDE.md`; `docs/dev-handoff-runbook.md`; `docs/templates/mock-round-protocol.md`' },
      { title: 'A retro the start hook counts.', detail: 'The hook prints RETRO DUE every ten sessions. `/retro` answers four questions with numbers and writes a dated file that resets the count.', file: '`.claude/settings.json`, `.claude/hooks/session-start.sh`, `.claude/commands/retro.md`' },
      { title: 'A local gate and a server gate.', detail: 'Required CI on a main ruleset with an empty bypass list makes the fast checks binding. The kit has no push hook: copy project-nyx\'s.', file: '`.github/workflows/ci.yml` from `ci.yml.template`; `.githooks/pre-push`' },
      { title: 'A lessons file, and a guard for every mistake that comes back.', detail: 'The byte ratchet first. Then a guard each time a fixed rule breaks again, proven by breaking the source on purpose.', file: '`docs/engineering-lessons.md`; `guards/` from the three `.template` files' },
      { title: 'Orchestration, once there is work for it.', detail: '`/dispatch` turns a run order into sessions; `/design-critique` runs isolated lenses with a verifier each. Installed before there is work, they become ceremony.', file: "`dispatch.md` (take project-nyx's live copy; the kit's predates the standing yes), `design-critique.md` and its workflow" },
    ],
  },

  footer: "The map of `operating-kit/` in `danieljmarkii/project-nyx`, a snapshot of 29 September 2026, checked against the repo on 2 October. Where this page and the kit's files disagree, the files win. Culprit's own instance, and where the kit has drifted from it: [The Culprit Operating Model](https://claude.ai/artifact/NA5jBZKbkC1egBsvTZyjxK), committed as `docs/how-we-work.html`.",
};
