// The capture-record CONTRACT — the shape both sides of the App-Group inbox
// agree on (B-290 W3 defined it; W4 splits it out).
//
// Deliberately dependency-free: the WRITER side (lib/widgetCapture.ts — the App
// Intents, running in the extension process) must not drag the app's SQLite /
// sync / supabase import graph into the widget bundle, and the READER side
// (lib/captureInbox.ts — the app's ingest) needs the same types and version
// constant. This module is the seam: types + version + filename convention
// only. Classification (the trust boundary) stays app-side in captureInbox.ts —
// the extension writes records, it never judges them.

import type { InboxLoggedVia } from './loggedVia';

// Bump when the record shape changes incompatibly. A record with a NEWER
// version than the app understands is DEFERRED (left in the inbox), never
// dropped — an extension binary can outrun the installed app's JS after a
// TestFlight update, and destroying its records would silently lose taps.
export const CAPTURE_INBOX_SCHEMA_VERSION = 1;

// 'bowl_topup' joins in W4 (its write shape is defined below). Adding a kind is
// NOT a schema-version bump: an older app JS defers an unknown kind rather than
// dropping it, so the record survives until the app catches up.
export type CaptureKind = 'meal' | 'treat' | 'bowl_topup';

// A meal/treat capture, as written by the extension. Ids are generated by the
// WRITER at tap time and are the canonical row ids everywhere (local SQLite,
// the sync upsert, any direct REST write) — that id-stability is what makes
// every leg of the pipeline idempotent.
export interface MealCaptureRecord {
  schemaVersion: number;
  /** The parent events row id — also the record's idempotency key + filename stem. */
  id: string;
  /** The child meals row id. */
  mealId: string;
  kind: 'meal' | 'treat';
  petId: string;
  /** The NAMED item (no-garbage rule D2) — required, never null. */
  foodItemId: string;
  /** Tap time, ISO UTC. Widget taps log "now" (spec §2.3). */
  occurredAt: string;
  loggedVia: InboxLoggedVia;
  /** Write time, ISO UTC — drives the unclaimable-record age-out. */
  createdAt: string;
}

// A bowl top-up (spec D6): an ARRANGEMENT event, never an intake claim. Its
// apply is a freshness re-attest of the pet's active free-choice
// arrangement(s) (confirmArrangementFresh's semantics) — no events row, no
// meals row, no intake anything, so it carries no mealId/foodItemId. The D2
// no-garbage rule is satisfied differently here: what the tap names is the
// standing fact itself (pet + "the bowl is down"), which is exactly what the
// apply touches. If the PM ever wants a discrete "topped up at 2p" timeline
// event, that is a schema addition — its own migration PR, not a reshape of
// this record.
export interface BowlTopUpCaptureRecord {
  schemaVersion: number;
  /** Idempotency key + filename stem (no row is inserted for this kind). */
  id: string;
  kind: 'bowl_topup';
  petId: string;
  /** Tap time, ISO UTC — becomes the arrangement's freshness stamp. */
  occurredAt: string;
  loggedVia: InboxLoggedVia;
  createdAt: string;
}

export type CaptureRecord = MealCaptureRecord | BowlTopUpCaptureRecord;

// One file per capture, named by the record's own id — the id-keyed filename is
// what makes an intent's retry (or a crash between write and confirm)
// overwrite its own record instead of duplicating it.
export function captureFileName(record: CaptureRecord): string {
  return `${record.id}.json`;
}
