// The App-Group capture inbox — the widget/intent → app write path (B-290, PR W3).
//
// The widget (W5) and its App Intents (W4) run in an extension process with no
// access to the app's SQLite file, so a Home Screen tap cannot write the record
// directly. Instead the extension appends ONE JSON FILE PER CAPTURE to the
// shared container's inbox (lib/appGroup.ts), and the app ingests those files
// into SQLite + the existing sync queue on the next foreground (hooks/useSync
// runs the ingest immediately before syncNow, so an ingested record rides that
// same cycle's push). The intent may ALSO attempt a direct Supabase REST write
// when online — the inbox is still written first and remains the source of
// truth for reconciliation: both paths use the SAME row ids (generated by the
// extension at tap time), so the local insert-if-absent + the id-keyed upsert
// converge on one row no matter which path lands first, and a record is only
// removed from the inbox once the app has durably applied it locally.
//
// Idempotency is the spine of the §4.1 "no lost taps" requirement: the ingest
// deletes a file only AFTER the rows are written, so a crash between apply and
// delete re-ingests the file next pass and the INSERT OR IGNORE no-ops. A tap
// is lost only if the extension's own file write fails — which the extension
// surfaces as a failed tap, never a silent one (W4/W5 contract).
//
// The no-garbage rule (spec D2) is enforced structurally: a record MUST name a
// food_item_id — there is no "generic treat, edit later" shape to parse, so an
// unnamed capture cannot exist in this pipeline. And provenance is narrowed to
// the inbox surfaces ('widget'/'intent' — lib/loggedVia.ts), so the inbox can
// never forge an in-app write.

import { getDb } from './db';
import { getCaptureInboxDirectory } from './appGroup';
import { triggerSignalRegenDebounced } from './signal';
import { isInboxLoggedVia, type InboxLoggedVia } from './loggedVia';

// Bump when the record shape changes incompatibly. A record with a NEWER
// version than the app understands is DEFERRED (left in the inbox), never
// dropped — an extension binary can outrun the installed app's JS after a
// TestFlight update, and destroying its records would silently lose taps.
export const CAPTURE_INBOX_SCHEMA_VERSION = 1;

// v1 kinds. 'bowl_topup' (the D6 arrangement event) is deliberately NOT here:
// its write shape is defined with the App Intents (W4); until then a record
// carrying it is an unknown kind and defers. Meals and treats share one shape —
// a treat IS a meal event whose food is food_type='treat' (the app's own model).
export type CaptureKind = 'meal' | 'treat';

// One capture, as written by the extension. Ids are generated by the WRITER at
// tap time and are the canonical row ids everywhere (local SQLite, the sync
// upsert, any direct REST write) — that id-stability is what makes every leg of
// the pipeline idempotent.
export interface CaptureRecord {
  schemaVersion: number;
  /** The parent events row id — also the record's idempotency key + filename stem. */
  id: string;
  /** The child meals row id. */
  mealId: string;
  kind: CaptureKind;
  petId: string;
  /** The NAMED item (no-garbage rule D2) — required, never null. */
  foodItemId: string;
  /** Tap time, ISO UTC. Widget taps log "now" (spec §2.3). */
  occurredAt: string;
  loggedVia: InboxLoggedVia;
  /** Write time, ISO UTC — drives the unclaimable-record age-out. */
  createdAt: string;
}

// A deferred record older than this is dropped as unclaimable — e.g. one naming
// a pet or food that no longer exists in the account. Generous on purpose: a
// deferral is usually transient (pet list not yet loaded, food cache not yet
// hydrated), and the cost of keeping a file for weeks is trivial next to the
// cost of destroying a real capture too early.
export const INBOX_MAX_AGE_DAYS = 45;

// Defense against a runaway writer filling the inbox: one pass ingests at most
// this many files; the remainder waits for the next foreground. Real usage is
// a handful of taps between foregrounds.
export const MAX_INGEST_PER_PASS = 200;

// What to do with one inbox file. 'defer' = leave it for a later pass (the
// blocker may be transient); 'drop' = delete it (it can never become
// ingestible); 'apply' = write the rows, then delete it.
export type InboxClassification =
  | { status: 'valid'; record: CaptureRecord }
  | { status: 'defer'; reason: string }
  | { status: 'drop'; reason: string };

const ISO_PARSEABLE = (v: unknown): v is string =>
  typeof v === 'string' && v.length > 0 && !Number.isNaN(Date.parse(v));

// Row-id shape guard. The extension generates v4-style uuids (the app's own
// lib/utils uuid format); anything else is rejected so a malformed id can never
// reach a SQL statement or a PostgREST upsert as a primary key.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Pure classification of one inbox payload — no I/O, unit-tested directly.
// Forward-compatibility rules (the reason defer exists at all):
//   • schemaVersion newer than ours → defer (an updated extension may be ahead
//     of the installed app JS; its records must survive until the app catches up);
//   • unknown kind on a current-version record → defer (same reasoning —
//     'bowl_topup' arrives with W4);
//   • anything structurally broken → drop (malformed JSON, bad ids, bad
//     timestamps, forged provenance — these can never become ingestible).
export function classifyInboxPayload(raw: string): InboxClassification {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { status: 'drop', reason: 'malformed JSON' };
  }
  if (typeof parsed !== 'object' || parsed === null) {
    return { status: 'drop', reason: 'not an object' };
  }
  const r = parsed as Record<string, unknown>;

  if (typeof r.schemaVersion !== 'number') {
    return { status: 'drop', reason: 'missing schemaVersion' };
  }
  if (r.schemaVersion > CAPTURE_INBOX_SCHEMA_VERSION) {
    return { status: 'defer', reason: `schemaVersion ${r.schemaVersion} newer than app` };
  }

  if (r.kind !== 'meal' && r.kind !== 'treat') {
    // Includes the reserved 'bowl_topup' — its write shape lands with W4.
    return { status: 'defer', reason: `unknown kind ${String(r.kind)}` };
  }

  if (typeof r.id !== 'string' || !UUID_RE.test(r.id)) {
    return { status: 'drop', reason: 'bad id' };
  }
  if (typeof r.mealId !== 'string' || !UUID_RE.test(r.mealId)) {
    return { status: 'drop', reason: 'bad mealId' };
  }
  if (typeof r.petId !== 'string' || !UUID_RE.test(r.petId)) {
    return { status: 'drop', reason: 'bad petId' };
  }
  // The no-garbage rule (D2): a capture that names nothing is not a capture.
  if (typeof r.foodItemId !== 'string' || !UUID_RE.test(r.foodItemId)) {
    return { status: 'drop', reason: 'missing/bad foodItemId' };
  }
  if (!ISO_PARSEABLE(r.occurredAt)) {
    return { status: 'drop', reason: 'bad occurredAt' };
  }
  if (!ISO_PARSEABLE(r.createdAt)) {
    return { status: 'drop', reason: 'bad createdAt' };
  }
  if (!isInboxLoggedVia(r.loggedVia)) {
    // 'app' (or anything else) here is a provenance forgery, not a version skew.
    return { status: 'drop', reason: `disallowed loggedVia ${String(r.loggedVia)}` };
  }

  return {
    status: 'valid',
    record: {
      schemaVersion: r.schemaVersion,
      id: r.id,
      mealId: r.mealId,
      kind: r.kind,
      petId: r.petId,
      foodItemId: r.foodItemId,
      occurredAt: r.occurredAt,
      createdAt: r.createdAt,
      loggedVia: r.loggedVia,
    },
  };
}

// The subset of the expo-sqlite surface the core ingest needs — narrowed so the
// real SQLiteDatabase satisfies it AND a node:sqlite adapter can in the unit
// test (the cacheFlush pattern: the production function runs against a real
// SQL engine in jest, not a copy of itself).
export interface InboxDb {
  runAsync(sql: string, params: (string | number | null)[]): Promise<unknown>;
  getFirstAsync<T>(sql: string, params: (string | number | null)[]): Promise<T | null>;
}

export interface InboxFilePayload {
  name: string;
  raw: string;
}

export type InboxAction = 'applied' | 'deferred' | 'dropped';

export interface InboxDecision {
  name: string;
  action: InboxAction;
  /** Set only for applied records — the pet whose Signal should refresh. */
  petId?: string;
  reason?: string;
}

// Core ingest over already-read payloads. Beyond the pure classification, two
// checks need the DB / account state:
//   • petId must be one of the account's own pets — a record naming a foreign
//     pet DEFERS (the pet list may simply not have loaded/hydrated yet; a truly
//     foreign record ages out via INBOX_MAX_AGE_DAYS rather than being written
//     into this account's record);
//   • foodItemId must exist in food_items_cache — otherwise the pushed meal
//     would FK-fail against food_items forever (the pre-sync can only re-upsert
//     foods the cache knows), poisoning the queue. Defers for the same
//     transient-until-aged-out reason (the cache hydrates each cycle).
// An empty validPetIds set skips the whole pass — it almost always means the
// pet list hasn't loaded, and running would wrongly defer/age every record.
export async function ingestCaptureRecords(
  db: InboxDb,
  files: InboxFilePayload[],
  validPetIds: ReadonlySet<string>,
  now: Date = new Date(),
): Promise<InboxDecision[]> {
  if (validPetIds.size === 0) {
    return files.map((f) => ({ name: f.name, action: 'deferred', reason: 'no pets loaded' }));
  }

  const decisions: InboxDecision[] = [];
  const maxAgeMs = INBOX_MAX_AGE_DAYS * 24 * 60 * 60 * 1000;

  for (const file of files) {
    const classified = classifyInboxPayload(file.raw);
    if (classified.status === 'drop') {
      decisions.push({ name: file.name, action: 'dropped', reason: classified.reason });
      continue;
    }
    if (classified.status === 'defer') {
      decisions.push({ name: file.name, action: 'deferred', reason: classified.reason });
      continue;
    }
    const record = classified.record;

    // Age-out: a record that has deferred past the window is unclaimable.
    // Checked before the defer paths below so a stale foreign-pet/missing-food
    // record eventually leaves the inbox instead of deferring forever.
    if (now.getTime() - Date.parse(record.createdAt) > maxAgeMs) {
      decisions.push({ name: file.name, action: 'dropped', reason: 'aged out' });
      continue;
    }

    if (!validPetIds.has(record.petId)) {
      decisions.push({ name: file.name, action: 'deferred', reason: 'pet not in account' });
      continue;
    }

    const food = await db.getFirstAsync<{ id: string }>(
      'SELECT id FROM food_items_cache WHERE id = ?',
      [record.foodItemId],
    );
    if (!food) {
      decisions.push({ name: file.name, action: 'deferred', reason: 'food not in cache' });
      continue;
    }

    // Apply — the insertMeal shape (lib/meals.ts), with the record's own ids and
    // provenance. INSERT OR IGNORE (not upsert): if the row already exists —
    // a re-ingest after a crash, or a second device that hydrated the intent's
    // direct REST write — the existing row wins untouched; an inbox record is a
    // creation, never an edit. Event before meal (meals.event_id FK). synced=0
    // queues both for the push that follows this ingest in the same cycle.
    // occurred_at_confidence 'witnessed' + occurred_at_source 'now': a widget
    // tap is the owner logging in the moment; the surface stamps the clock.
    const nowIso = now.toISOString();
    await db.runAsync(
      `INSERT OR IGNORE INTO events
         (id, pet_id, event_type, occurred_at, severity, notes, source, occurred_at_source,
          occurred_at_confidence, occurred_at_earliest, occurred_at_latest,
          logged_via, created_at, updated_at, synced)
       VALUES (?, ?, 'meal', ?, NULL, NULL, 'manual', 'now', 'witnessed', NULL, NULL, ?, ?, ?, 0)`,
      [record.id, record.petId, record.occurredAt, record.loggedVia, record.createdAt, nowIso],
    );
    // Assumed portion, unrated (spec §2.3): quantity 'unknown', no
    // intake_rating — a widget tap is not a witnessed rating, and the engine
    // must never conflate the two (§3).
    await db.runAsync(
      `INSERT OR IGNORE INTO meals
         (id, event_id, pet_id, food_item_id, quantity, logged_via, created_at, updated_at, synced)
       VALUES (?, ?, ?, ?, 'unknown', ?, ?, ?, 0)`,
      [record.mealId, record.id, record.petId, record.foodItemId, record.loggedVia, record.createdAt, nowIso],
    );
    await db.runAsync('UPDATE food_items_cache SET last_used_at = ? WHERE id = ?', [
      nowIso,
      record.foodItemId,
    ]);

    decisions.push({ name: file.name, action: 'applied', petId: record.petId });
  }

  return decisions;
}

// The file-system wrapper the app actually calls (hooks/useSync, immediately
// before syncNow so applied records ride the same cycle's push). Reads the
// inbox, runs the core ingest, deletes applied+dropped files, leaves deferred
// ones, and refreshes the Signal for each pet that gained a record. Every step
// is best-effort per file — one unreadable file must not strand the rest.
export async function ingestCaptureInbox(validPetIds: ReadonlySet<string>): Promise<void> {
  const inbox = getCaptureInboxDirectory();
  if (!inbox) return; // Android / no entitlement — the surface doesn't exist here.

  let entries;
  try {
    entries = inbox.list();
  } catch (e) {
    console.warn('[captureInbox] inbox list failed:', e);
    return;
  }

  const files: InboxFilePayload[] = [];
  const byName = new Map<string, { delete(): void }>();
  for (const entry of entries) {
    // Only files, only .json — the extension writes nothing else; anything else
    // is left alone rather than guessed at.
    if (!('textSync' in entry) || !entry.name.endsWith('.json')) continue;
    if (files.length >= MAX_INGEST_PER_PASS) break;
    try {
      files.push({ name: entry.name, raw: entry.textSync() });
      byName.set(entry.name, entry);
    } catch (e) {
      console.warn(`[captureInbox] read failed for ${entry.name}:`, e);
    }
  }
  if (files.length === 0) return;

  let decisions: InboxDecision[];
  try {
    decisions = await ingestCaptureRecords(getDb(), files, validPetIds);
  } catch (e) {
    // A throw mid-pass leaves every file in place; the next foreground retries
    // and INSERT OR IGNORE makes any half-applied record a no-op.
    console.warn('[captureInbox] ingest failed:', e);
    return;
  }

  const regenPets = new Set<string>();
  for (const d of decisions) {
    if (d.action === 'deferred') {
      // Deferrals are expected to be transient; log so a stuck record (e.g. a
      // genuinely foreign pet waiting on the age-out) is visible in the trail.
      console.warn(`[captureInbox] deferred ${d.name}: ${d.reason}`);
      continue;
    }
    if (d.action === 'dropped') {
      console.warn(`[captureInbox] dropped ${d.name}: ${d.reason}`);
    }
    if (d.action === 'applied' && d.petId) regenPets.add(d.petId);
    try {
      byName.get(d.name)?.delete();
    } catch (e) {
      // Delete failed after a durable apply — the re-ingest next pass no-ops.
      console.warn(`[captureInbox] delete failed for ${d.name}:`, e);
    }
  }

  // A new meal can change the cached insight set (same reasoning as insertMeal);
  // debounced so a burst of widget taps collapses into one regen per pet.
  for (const petId of regenPets) triggerSignalRegenDebounced(petId);
}
