import { useCallback, useRef, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { usePetStore } from '../store/petStore';
import { regenerateSignal } from '../lib/signal';
import { readSummaryCache } from '../lib/summary';
import {
  isSummaryCacheStale,
  deriveSummaryState,
  type CachedSummary,
  type SummaryDisplayState,
} from '../lib/summaryCopy';

export interface SummaryState {
  summary: CachedSummary | null;
  displayState: SummaryDisplayState;
  petName: string;
  isLoading: boolean;
}

// The dashboard AI summary. CACHE-ONLY on open — reads the CachedSummary the generate-signal
// Edge Function wrote to ai_signals.summary; it never makes a live LLM call (requirements §7).
// The summary shares the ai_signals row with the home Signal's findings/coverage and is
// regenerated by the SAME function, so when the cache is missing/expired this kicks the shared
// regenerateSignal() (daily-expiry) and re-reads when it lands — the last cached summary, or the
// building state, shows meanwhile. Mirrors hooks/useSignal.ts.
export function useSummary(): SummaryState {
  const { activePet } = usePetStore();
  const [summary, setSummary] = useState<CachedSummary | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const loadedPetRef = useRef<string | null>(null);

  const petId = activePet?.id ?? null;
  const petName = activePet?.name ?? 'your pet';

  useFocusEffect(
    useCallback(() => {
      if (!petId) return;
      let cancelled = false;
      const firstLoad = loadedPetRef.current !== petId;
      loadedPetRef.current = petId;
      // On a pet SWITCH, clear the previous pet's summary so it can't flash on the new pet
      // during the async read (multi-pet safety — the summary names a real pet + numbers).
      if (firstLoad) {
        setIsLoading(true);
        setSummary(null);
      }

      (async () => {
        try {
          const row = await readSummaryCache(petId);
          if (cancelled) return;
          setSummary(row?.summary ?? null);

          if (isSummaryCacheStale(row)) {
            // Daily-expiry regen — off the render path; re-read when it lands.
            regenerateSignal(petId)
              .then(() => readSummaryCache(petId))
              .then((fresh) => {
                if (cancelled || !fresh) return;
                setSummary(fresh.summary);
              })
              .catch(() => {});
          }
        } catch {
          // Cache unreadable (offline / function not yet deployed) — keep the last state;
          // the derived building state stays honest, never an all-clear.
        } finally {
          if (!cancelled) setIsLoading(false);
        }
      })();

      return () => {
        cancelled = true;
      };
    }, [petId]),
  );

  return { summary, displayState: deriveSummaryState(summary), petName, isLoading };
}
