// The Board (CUL-1615): Out of beta's, as of 2026-10-05T12:35Z, without the three defects
// the prose-written one carried, and the parse that refuses the one it actually wrote.

import * as F from './fixtures/facts-2026-10-05.ts';
import { markPath, renderBoard, shortReason, validateBoard } from './board.ts';
import { stripTags } from './page.ts';
import { planDispatch } from './plan.ts';

const NOW = '2026-10-05T12:35:00Z';
const plan = planDispatch({
  now: NOW,
  project: F.OUT_OF_BETA,
  others: [F.ENGINES_V3],
  prs: [...F.MERGED.filter((p) => p.mergedAt! <= NOW), F.PR_1064],
  issues: F.ISSUES,
  claims: [],
  sessions: F.SESSIONS_AT_2110,
  launches: F.LAUNCHES.filter((l) => l.at <= NOW),
  mainMigrations: F.MAIN_MIGRATIONS_THROUGH_083,
  productionLib: F.PRODUCTION_LIB,
});
const merged = new Set(plan.verdicts.filter((v) => v.state.kind === 'merged').map((v) => v.row));
const facts = { now: NOW, merged, rows: new Set(plan.verdicts.map((v) => v.row)) };
const board = renderBoard({ plan, now: NOW, shape: 'table' });
const line = (id: string) => board.split('\n').find((l) => l.startsWith(`| ${id} |`));

describe('the Out of beta Board, 2026-10-05T12:35Z', () => {
  it('defect 1: every row is a whole line of plain ids (was `| 12 | </pull-request> |`)', () => {
    expect(board).not.toMatch(/<\/?(issue|pull-request)/);
    expect(board.split('\n').filter((l) => l.startsWith('| 12 |'))).toEqual(['| 12 | CUL-909 | ✓ #1022 |']);
    for (const l of board.split('\n').filter((x) => x.startsWith('|'))) expect(l.split('|').slice(1, -1)).toHaveLength(3);
  });

  it('defect 2: PR-61 is not "waiting on PR-53", which merged; it waits on the PR holding its files', () => {
    expect(line('61')).toBe('| 61 | CUL-1521 | waiting on #1064 (CLAUDE.md) |');
    expect(line('53')).toBe('| 53 | CUL-1071 | ✓ #1070 |');
  });

  it('defect 3: the path to GA carries a ✓ on every merged PR', () => {
    expect(board).toContain('to GA: PR-50 ✓ → PR-51 ✓ → PR-52 ✓ → PR-53 ✓ → PR-61');
  });

  it('parses clean', () => {
    expect(validateBoard(board, facts)).toEqual([]);
  });

  it('the Board the prose wrote that day is refused, for each of its three defects', () => {
    const lines = F.OUT_OF_BETA.description.split('\n');
    const from = lines.indexOf('## Board');
    const to = lines.findIndex((l, i) => i > from && l.startsWith('## '));
    const written = stripTags(lines.slice(from, to).join('\n')).replace('*Generated by', '_Generated by').replace('never here.*', 'never here._');
    const errors = validateBoard(written, facts);
    expect(errors).toContain('a link tag (or a fragment of one) is in the Board');
    expect(errors).toContain('row 61 is "waiting on" PR-53, which has merged');
    for (const r of ['11b', '50', '51', '52', '53']) expect(errors).toContain(`PR-${r} has merged and carries no ✓ on the critical path`);
  });
});

describe('the digest shape (D4: the PM reads the digests)', () => {
  const digest = renderBoard({ plan, now: NOW, shape: 'digest' });
  it('is six lines in the PM words, no table and no path', () => {
    expect(digest.split('\n').filter((l) => l.startsWith('* **')).map((l) => /\*\*(.+?):\*\*/.exec(l)![1])).toEqual([
      'Needs you', 'Running', 'Next', 'Unblock', 'For you', 'Waves done',
    ]);
    expect(digest).not.toMatch(/^\|/m);
    expect(digest).not.toContain('Critical path');
    expect(digest).toContain('* **Waves done:** Wave 1 · Noticed ✓; Wave 1 · Design v2 ✓; Wave 1 · History v2 ✓; Wave 1 · the trial screen ✓; Wave 2 · the sitting and GA: 4 of 6');
    expect(validateBoard(digest, facts)).toEqual([]);
  });
});

describe('validation', () => {
  it('refuses a stamp ahead of the clock', () => {
    const ahead = board.replace(NOW, '2026-10-05T13:35:00Z');
    expect(validateBoard(ahead, facts)).toEqual(['the stamp 2026-10-05T13:35:00Z is ahead of the clock (2026-10-05T12:35:00Z)']);
  });

  it('refuses a malformed row and a ✓ with no number', () => {
    expect(validateBoard(board.replace('| 12 | CUL-909 | ✓ #1022 |', '| 12 | CUL-909 | ✓ a title |'), facts)).toEqual([
      'row 12\'s ✓ carries no PR number: "✓ a title"',
    ]);
    expect(validateBoard(board.replace('| 12 | CUL-909 | ✓ #1022 |', '| 12 | ✓ #1022 |'), facts)[0]).toMatch(/^a malformed table line/);
  });
});

it('markPath marks merged rows, unmarks unmerged ones', () => {
  expect(markPath('PR-50 ✓ → PR-61 ✓', (r) => r === '50')).toBe('PR-50 ✓ → PR-61');
});

it.each([
  ['after PR-31, not merged', 'PR-31'],
  ['hotspot CLAUDE.md is held by #1064 (PR-60, parked)', '#1064 (CLAUDE.md)'],
  ['a ruling: "ruling sheet drug and age items"', 'ruling: ruling sheet drug'],
])('shortReason(%s)', (r, s) => expect(shortReason(r)).toBe(s));

it('a row with no readable PR number still renders a Board that parses (found by review)', () => {
  const p = planDispatch({
    now: NOW,
    project: { name: 'Tiny', description: '| PR | Issue(s) | What it is | After | Lane |\n| -- | -- | -- | -- | -- |\n| ? | CUL-10 | one | — | A |\n| 01 | CUL-11 | two | — | A |\n\n## End\n' },
    prs: [], issues: {}, claims: [], sessions: {}, launches: [], mainMigrations: [],
  });
  const b = renderBoard({ plan: p, now: NOW, shape: 'table' });
  expect(b).toContain('| — | CUL-10 | not a row |');
  expect(validateBoard(b, { now: NOW, merged: new Set(), rows: new Set(['01']) })).toEqual([]);
});
