// Supabase Edge Function — generate-report
// Builds a clinical-grade PDF vet report for a given pet and date range.
// Uses the caller's JWT for all data reads (RLS enforces ownership).
// Uses the service role key only for storage uploads.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { PDFDocument, StandardFonts, rgb } from 'https://esm.sh/pdf-lib@1.17.1'

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface PetRow {
  id: string
  name: string
  species: string
  breed: string | null
  date_of_birth: string | null
  sex: string
  weight_kg: number | null
}

interface EventRow {
  id: string
  event_type: string
  occurred_at: string
  severity: number | null
  notes: string | null
}

interface MealRow {
  event_id: string
  quantity: string
  food_items: { brand: string; product_name: string } | null
}

interface ConditionRow {
  condition_name: string
  status: string
  diagnosed_at: string | null
}

interface DietTrialRow {
  started_at: string
  target_duration_days: number
  food_items: { brand: string; product_name: string } | null
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function formatDate(isoDate: string): string {
  const d = new Date(isoDate.includes('T') ? isoDate : isoDate + 'T00:00:00Z')
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' })
}

function formatDateTime(iso: string): string {
  const d = new Date(iso)
  const date = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' })
  const time = d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true, timeZone: 'UTC' })
  return `${date}  ${time}`
}

function calcAge(dob: string): string {
  const birth = new Date(dob + 'T00:00:00Z')
  const now = new Date()
  const months = (now.getFullYear() - birth.getFullYear()) * 12 + (now.getMonth() - birth.getMonth())
  if (months < 12) return `${months}mo`
  const yrs = Math.floor(months / 12)
  const mo = months % 12
  return mo > 0 ? `${yrs}yr ${mo}mo` : `${yrs}yr`
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

// ── PDF generation ───────────────────────────────────────────────────────────

const PAGE_W = 612
const PAGE_H = 792
const MARGIN = 72
const CONTENT_W = PAGE_W - 2 * MARGIN

const C_TEXT = rgb(0.10, 0.10, 0.10)
const C_SECONDARY = rgb(0.42, 0.42, 0.42)
const C_RULE = rgb(0.88, 0.88, 0.88)
const C_FOOTER = rgb(0.65, 0.65, 0.65)

const EVENT_LABELS: Record<string, string> = {
  meal: 'Meals',
  vomit: 'Vomiting',
  diarrhea: 'Diarrhea',
  stool_normal: 'Normal stool',
  lethargy: 'Lethargy',
  itch: 'Itch / Scratch',
  scratch: 'Scratch',
  skin_reaction: 'Skin reaction',
  medication: 'Medication',
  other: 'Other',
}

const SYMPTOM_TYPES = new Set(['vomit', 'diarrhea', 'lethargy', 'itch', 'scratch', 'skin_reaction'])

async function buildPdf(params: {
  pet: PetRow
  events: EventRow[]
  mealMap: Map<string, MealRow>
  conditions: ConditionRow[]
  dietTrial: DietTrialRow | null
  dateRangeStart: string
  dateRangeEnd: string
}): Promise<Uint8Array> {
  const { pet, events, mealMap, conditions, dietTrial, dateRangeStart, dateRangeEnd } = params

  const pdfDoc = await PDFDocument.create()
  const regular = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  let page = pdfDoc.addPage([PAGE_W, PAGE_H])
  let y = PAGE_H - MARGIN

  // Ensure there is enough vertical space; add a new page if not.
  function ensureSpace(needed: number) {
    if (y - needed < MARGIN + 36) {
      // Draw footer on the current page before adding a new one
      drawFooter(page)
      page = pdfDoc.addPage([PAGE_W, PAGE_H])
      y = PAGE_H - MARGIN
    }
  }

  function drawFooter(p: typeof page) {
    p.drawLine({
      start: { x: MARGIN, y: MARGIN + 16 },
      end: { x: PAGE_W - MARGIN, y: MARGIN + 16 },
      thickness: 0.5,
      color: C_RULE,
    })
    p.drawText(
      `Generated by Nyx  ·  nyx.app  ·  ${formatDate(dateRangeStart)} – ${formatDate(dateRangeEnd)}`,
      { x: MARGIN, y: MARGIN, size: 8, font: regular, color: C_FOOTER },
    )
  }

  function line(text: string, x: number, size: number, font: typeof regular, color = C_TEXT, moveY = true) {
    page.drawText(text, { x, y, size, font, color })
    if (moveY) y -= Math.round(size * 1.5)
  }

  function rule() {
    y -= 6
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: C_RULE })
    y -= 10
  }

  function sectionHeader(title: string) {
    ensureSpace(32)
    y -= 6
    page.drawText(title.toUpperCase(), { x: MARGIN, y, size: 8, font: bold, color: C_SECONDARY, characterSpacing: 0.8 })
    y -= 12
    rule()
  }

  // ── Title block ─────────────────────────────────────────────────────────────
  line('HEALTH SUMMARY', MARGIN, 18, bold)
  y -= 2
  line(pet.name, MARGIN, 13, regular, C_SECONDARY)
  y += 2
  line(`${formatDate(dateRangeStart)} – ${formatDate(dateRangeEnd)}`, MARGIN, 10, regular, C_SECONDARY)
  line(`Generated ${formatDate(new Date().toISOString().split('T')[0])}`, MARGIN, 9, regular, C_FOOTER)
  y -= 10

  // ── Patient ─────────────────────────────────────────────────────────────────
  sectionHeader('Patient')

  const petParts: string[] = [
    capitalize(pet.species),
    pet.breed ?? null,
    pet.date_of_birth ? `Age ${calcAge(pet.date_of_birth)}` : null,
    pet.sex !== 'unknown' ? capitalize(pet.sex) : null,
    pet.weight_kg != null ? `${(pet.weight_kg * 2.20462).toFixed(1)} lbs` : null,
  ].filter(Boolean) as string[]
  line(petParts.join('  ·  '), MARGIN, 10, regular)
  y -= 4

  // ── Event summary ────────────────────────────────────────────────────────────
  sectionHeader('Event Summary')

  const counts: Record<string, number> = {}
  const severity: Record<string, { sum: number; n: number }> = {}
  for (const e of events) {
    counts[e.event_type] = (counts[e.event_type] ?? 0) + 1
    if (e.severity != null && SYMPTOM_TYPES.has(e.event_type)) {
      const s = severity[e.event_type] ?? { sum: 0, n: 0 }
      severity[e.event_type] = { sum: s.sum + e.severity, n: s.n + 1 }
    }
  }

  if (events.length === 0) {
    line('No events logged in this period.', MARGIN, 10, regular, C_SECONDARY)
  } else {
    for (const [type, count] of Object.entries(counts).sort()) {
      ensureSpace(18)
      const label = EVENT_LABELS[type] ?? capitalize(type)
      const countStr = `${count} event${count !== 1 ? 's' : ''}`
      const avgStr = severity[type]
        ? `   avg severity ${(severity[type].sum / severity[type].n).toFixed(1)} / 5`
        : ''
      page.drawText(label, { x: MARGIN, y, size: 10, font: regular, color: C_TEXT })
      page.drawText(countStr + avgStr, { x: MARGIN + 160, y, size: 10, font: regular, color: C_SECONDARY })
      y -= 16
    }
  }
  y -= 4

  // ── Meal log ─────────────────────────────────────────────────────────────────
  const mealEvents = events.filter(e => e.event_type === 'meal')
  if (mealEvents.length > 0) {
    sectionHeader('Meal Log')
    for (const e of mealEvents) {
      ensureSpace(15)
      const m = mealMap.get(e.id)
      const food = m?.food_items ? `${m.food_items.brand} ${m.food_items.product_name}` : 'Food not recorded'
      const qty = m?.quantity && m.quantity !== 'unknown' ? `  ·  ${m.quantity.replace(/_/g, ' ')}` : ''
      page.drawText(formatDateTime(e.occurred_at), { x: MARGIN, y, size: 9, font: regular, color: C_SECONDARY })
      page.drawText(food + qty, { x: MARGIN + 120, y, size: 9, font: regular, color: C_TEXT })
      y -= 14
    }
    y -= 4
  }

  // ── Conditions ───────────────────────────────────────────────────────────────
  const activeConditions = conditions.filter(c => c.status !== 'resolved')
  if (activeConditions.length > 0) {
    sectionHeader('Known Conditions')
    for (const c of activeConditions) {
      ensureSpace(18)
      const status = c.status === 'monitoring' ? 'Monitoring' : 'Active'
      const diagnosed = c.diagnosed_at ? `  ·  Diagnosed ${formatDate(c.diagnosed_at)}` : ''
      page.drawText(c.condition_name, { x: MARGIN, y, size: 10, font: bold, color: C_TEXT })
      page.drawText(status + diagnosed, { x: MARGIN + 180, y, size: 9, font: regular, color: C_SECONDARY })
      y -= 16
    }
    y -= 4
  }

  // ── Diet trial ───────────────────────────────────────────────────────────────
  if (dietTrial) {
    sectionHeader('Diet Trial')
    ensureSpace(60)
    const food = dietTrial.food_items
      ? `${dietTrial.food_items.brand} ${dietTrial.food_items.product_name}`
      : 'Protocol food not recorded'
    const daysElapsed = Math.max(1, Math.floor((Date.now() - new Date(dietTrial.started_at).getTime()) / 86_400_000))
    const loggedDays = new Set(
      mealEvents
        .filter(e => e.occurred_at >= dietTrial.started_at)
        .map(e => e.occurred_at.split('T')[0]),
    ).size
    const compliance = Math.round((loggedDays / daysElapsed) * 100)

    line(food, MARGIN, 10, bold)
    line(
      `Day ${daysElapsed} of ${dietTrial.target_duration_days}  ·  ${compliance}% compliance  ·  ${loggedDays} of ${daysElapsed} days with meals logged`,
      MARGIN, 9, regular, C_SECONDARY,
    )
    line(`Trial start: ${formatDate(dietTrial.started_at)}`, MARGIN, 9, regular, C_SECONDARY)
    y -= 4
  }

  // ── Footer on last page ───────────────────────────────────────────────────────
  const pages = pdfDoc.getPages()
  drawFooter(pages[pages.length - 1])

  return pdfDoc.save()
}

// ── Handler ──────────────────────────────────────────────────────────────────

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: CORS_HEADERS })
  }

  try {
    const body = await req.json() as { petId?: string; dateRangeStart?: string; dateRangeEnd?: string }
    const { petId, dateRangeStart, dateRangeEnd } = body

    if (!petId || !dateRangeStart || !dateRangeEnd) {
      return Response.json({ error: 'petId, dateRangeStart, dateRangeEnd required' }, { status: 400, headers: CORS_HEADERS })
    }

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return Response.json({ error: 'Unauthorized' }, { status: 401, headers: CORS_HEADERS })
    }

    // Caller's JWT for data reads — RLS enforces pet ownership
    const userClient = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } },
    )

    // Service role for storage writes only
    const serviceClient = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    )

    // Validate JWT and extract user id
    const { data: { user }, error: userError } = await userClient.auth.getUser()
    if (userError || !user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401, headers: CORS_HEADERS })
    }

    // Inclusive date range — endDate covers the full day in UTC
    const startISO = new Date(dateRangeStart + 'T00:00:00Z').toISOString()
    const endISO = new Date(dateRangeEnd + 'T23:59:59Z').toISOString()

    // Fetch all required data in parallel
    const [petResult, eventsResult, conditionsResult, dietTrialResult] = await Promise.all([
      userClient
        .from('pets')
        .select('id, name, species, breed, date_of_birth, sex, weight_kg')
        .eq('id', petId)
        .single<PetRow>(),

      userClient
        .from('events')
        .select('id, event_type, occurred_at, severity, notes')
        .eq('pet_id', petId)
        .is('deleted_at', null)
        .gte('occurred_at', startISO)
        .lte('occurred_at', endISO)
        .order('occurred_at', { ascending: true })
        .returns<EventRow[]>(),

      userClient
        .from('conditions')
        .select('condition_name, status, diagnosed_at')
        .eq('pet_id', petId)
        .neq('status', 'resolved')
        .returns<ConditionRow[]>(),

      userClient
        .from('diet_trials')
        .select('started_at, target_duration_days, food_items(brand, product_name)')
        .eq('pet_id', petId)
        .eq('status', 'active')
        .limit(1)
        .maybeSingle<DietTrialRow>(),
    ])

    if (petResult.error || !petResult.data) {
      return Response.json({ error: 'Pet not found or access denied' }, { status: 404, headers: CORS_HEADERS })
    }

    const events = eventsResult.data ?? []

    // Fetch meal details for meal events
    const mealEventIds = events.filter(e => e.event_type === 'meal').map(e => e.id)
    const mealMap = new Map<string, MealRow>()

    if (mealEventIds.length > 0) {
      const { data: meals } = await userClient
        .from('meals')
        .select('event_id, quantity, food_items(brand, product_name)')
        .in('event_id', mealEventIds)
        .returns<MealRow[]>()

      for (const m of meals ?? []) {
        mealMap.set(m.event_id, m)
      }
    }

    // Generate the PDF
    const pdfBytes = await buildPdf({
      pet: petResult.data,
      events,
      mealMap,
      conditions: conditionsResult.data ?? [],
      dietTrial: dietTrialResult.data ?? null,
      dateRangeStart,
      dateRangeEnd,
    })

    // Upload PDF to storage using service role (bypasses storage RLS)
    const reportId = crypto.randomUUID()
    const storagePath = `${petId}/${reportId}.pdf`

    const { error: uploadError } = await serviceClient.storage
      .from('nyx-vet-reports')
      .upload(storagePath, pdfBytes, { contentType: 'application/pdf', upsert: false })

    if (uploadError) {
      throw new Error(`Storage upload failed: ${uploadError.message}`)
    }

    // Signed URL valid for 30 days — this is the share URL for MVP
    const { data: signed, error: signedError } = await serviceClient.storage
      .from('nyx-vet-reports')
      .createSignedUrl(storagePath, 30 * 24 * 60 * 60)

    if (signedError || !signed) {
      throw new Error('Failed to create signed URL')
    }

    // Record the report in vet_reports (uses user client so generated_by = auth.uid())
    const tokenExpiresAt = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString()
    const { data: reportRow, error: reportError } = await userClient
      .from('vet_reports')
      .insert({
        pet_id: petId,
        generated_by: user.id,
        date_range_start: dateRangeStart,
        date_range_end: dateRangeEnd,
        storage_path: storagePath,
        token_expires_at: tokenExpiresAt,
      })
      .select('share_token')
      .single()

    if (reportError || !reportRow) {
      throw new Error(`Failed to record report: ${reportError?.message}`)
    }

    return Response.json({
      share_token: reportRow.share_token,
      share_url: signed.signedUrl,
      storage_path: storagePath,
    }, { headers: CORS_HEADERS })

  } catch (err) {
    console.error('[generate-report] error:', err)
    return Response.json({ error: 'Report generation failed' }, { status: 500, headers: CORS_HEADERS })
  }
})
